# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: shell_session_manager/shellctl/proto/v1/shellctl.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.client
import grpclib.const

if typing.TYPE_CHECKING:
    import grpclib.server

import shell_session_manager.shellctl.proto.v1.shellctl_pb2


class ShellctlBase(abc.ABC):
    @abc.abstractmethod
    async def Health(
        self,
        stream: "grpclib.server.Stream[shell_session_manager.shellctl.proto.v1.shellctl_pb2.HealthRequest, shell_session_manager.shellctl.proto.v1.shellctl_pb2.HealthResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def RunJob(
        self,
        stream: "grpclib.server.Stream[shell_session_manager.shellctl.proto.v1.shellctl_pb2.RunJobRequest, shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def WaitJob(
        self,
        stream: "grpclib.server.Stream[shell_session_manager.shellctl.proto.v1.shellctl_pb2.WaitJobRequest, shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def TailJob(
        self,
        stream: "grpclib.server.Stream[shell_session_manager.shellctl.proto.v1.shellctl_pb2.TailJobRequest, shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def GetJobStatus(
        self,
        stream: "grpclib.server.Stream[shell_session_manager.shellctl.proto.v1.shellctl_pb2.GetJobStatusRequest, shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobStatusView]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ListJobs(
        self,
        stream: "grpclib.server.Stream[shell_session_manager.shellctl.proto.v1.shellctl_pb2.ListJobsRequest, shell_session_manager.shellctl.proto.v1.shellctl_pb2.ListJobsResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SendInput(
        self,
        stream: "grpclib.server.Stream[shell_session_manager.shellctl.proto.v1.shellctl_pb2.InputJobRequest, shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def TerminateJob(
        self,
        stream: "grpclib.server.Stream[shell_session_manager.shellctl.proto.v1.shellctl_pb2.TerminateJobRequest, shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobStatusView]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def DeleteJob(
        self,
        stream: "grpclib.server.Stream[shell_session_manager.shellctl.proto.v1.shellctl_pb2.DeleteJobRequest, shell_session_manager.shellctl.proto.v1.shellctl_pb2.DeleteJobResponse]",
    ) -> None:
        pass

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/shellctl.v1.Shellctl/Health": grpclib.const.Handler(
                self.Health,
                grpclib.const.Cardinality.UNARY_UNARY,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.HealthRequest,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.HealthResponse,
            ),
            "/shellctl.v1.Shellctl/RunJob": grpclib.const.Handler(
                self.RunJob,
                grpclib.const.Cardinality.UNARY_UNARY,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.RunJobRequest,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult,
            ),
            "/shellctl.v1.Shellctl/WaitJob": grpclib.const.Handler(
                self.WaitJob,
                grpclib.const.Cardinality.UNARY_UNARY,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.WaitJobRequest,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult,
            ),
            "/shellctl.v1.Shellctl/TailJob": grpclib.const.Handler(
                self.TailJob,
                grpclib.const.Cardinality.UNARY_UNARY,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.TailJobRequest,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult,
            ),
            "/shellctl.v1.Shellctl/GetJobStatus": grpclib.const.Handler(
                self.GetJobStatus,
                grpclib.const.Cardinality.UNARY_UNARY,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.GetJobStatusRequest,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobStatusView,
            ),
            "/shellctl.v1.Shellctl/ListJobs": grpclib.const.Handler(
                self.ListJobs,
                grpclib.const.Cardinality.UNARY_UNARY,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.ListJobsRequest,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.ListJobsResponse,
            ),
            "/shellctl.v1.Shellctl/SendInput": grpclib.const.Handler(
                self.SendInput,
                grpclib.const.Cardinality.UNARY_UNARY,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.InputJobRequest,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult,
            ),
            "/shellctl.v1.Shellctl/TerminateJob": grpclib.const.Handler(
                self.TerminateJob,
                grpclib.const.Cardinality.UNARY_UNARY,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.TerminateJobRequest,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobStatusView,
            ),
            "/shellctl.v1.Shellctl/DeleteJob": grpclib.const.Handler(
                self.DeleteJob,
                grpclib.const.Cardinality.UNARY_UNARY,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.DeleteJobRequest,
                shell_session_manager.shellctl.proto.v1.shellctl_pb2.DeleteJobResponse,
            ),
        }


class ShellctlStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Health = grpclib.client.UnaryUnaryMethod(
            channel,
            "/shellctl.v1.Shellctl/Health",
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.HealthRequest,
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.HealthResponse,
        )
        self.RunJob = grpclib.client.UnaryUnaryMethod(
            channel,
            "/shellctl.v1.Shellctl/RunJob",
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.RunJobRequest,
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult,
        )
        self.WaitJob = grpclib.client.UnaryUnaryMethod(
            channel,
            "/shellctl.v1.Shellctl/WaitJob",
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.WaitJobRequest,
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult,
        )
        self.TailJob = grpclib.client.UnaryUnaryMethod(
            channel,
            "/shellctl.v1.Shellctl/TailJob",
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.TailJobRequest,
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult,
        )
        self.GetJobStatus = grpclib.client.UnaryUnaryMethod(
            channel,
            "/shellctl.v1.Shellctl/GetJobStatus",
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.GetJobStatusRequest,
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobStatusView,
        )
        self.ListJobs = grpclib.client.UnaryUnaryMethod(
            channel,
            "/shellctl.v1.Shellctl/ListJobs",
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.ListJobsRequest,
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.ListJobsResponse,
        )
        self.SendInput = grpclib.client.UnaryUnaryMethod(
            channel,
            "/shellctl.v1.Shellctl/SendInput",
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.InputJobRequest,
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobResult,
        )
        self.TerminateJob = grpclib.client.UnaryUnaryMethod(
            channel,
            "/shellctl.v1.Shellctl/TerminateJob",
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.TerminateJobRequest,
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.JobStatusView,
        )
        self.DeleteJob = grpclib.client.UnaryUnaryMethod(
            channel,
            "/shellctl.v1.Shellctl/DeleteJob",
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.DeleteJobRequest,
            shell_session_manager.shellctl.proto.v1.shellctl_pb2.DeleteJobResponse,
        )
