"""Shared shellctl transport/runtime helpers.

The original `shell_session_manager.shellctl.shared` module is now a package so
constants, DTOs, runtime naming helpers, UTF-8-safe output slicing, and PTY
sanitize logic can live in smaller files while callers keep the same import
surface.
"""

from shell_session_manager.shellctl.shared.constants import (
    DEFAULT_AUTH_TOKEN_ENV,
    DEFAULT_GC_FINISHED_JOB_RETENTION_SECONDS,
    DEFAULT_GC_INTERVAL_SECONDS,
    DEFAULT_HEALTH_STATUS,
    DEFAULT_IDLE_FLUSH_SECONDS,
    DEFAULT_LIST_LIMIT,
    DEFAULT_OUTPUT_LIMIT_BYTES,
    DEFAULT_TERMINAL_COLS,
    DEFAULT_TERMINAL_ROWS,
    DEFAULT_TERMINATE_GRACE_SECONDS,
    DEFAULT_TIMEOUT_SECONDS,
    JOB_ID_ALPHABET,
    JOB_ID_RANDOM_SUFFIX_LENGTH,
    MAX_LIST_LIMIT,
    MAX_OUTPUT_LIMIT_BYTES,
    MAX_WAIT_TIMEOUT_SECONDS,
    SESSION_NAME_PREFIX,
)
from shell_session_manager.shellctl.shared.output import (
    OutputWindow,
    read_output_window,
    tail_output_window,
)
from shell_session_manager.shellctl.shared.runtime import (
    default_runtime_dir,
    default_state_dir,
    format_timestamp,
    generate_job_id,
    is_terminal_status,
    job_pane_target,
    job_session_name,
    parse_timestamp,
    utc_now,
)
from shell_session_manager.shellctl.shared.sanitize import (
    PtySanitizer,
    sanitize_pty_output,
    sanitize_pty_stream,
)
from shell_session_manager.shellctl.shared.schemas import (
    TERMINAL_JOB_STATUSES,
    DeleteJobResponse,
    ErrorDetail,
    ErrorResponse,
    HealthResponse,
    InputJobRequest,
    JobInfo,
    JobResult,
    JobStatusName,
    JobStatusView,
    ListJobsResponse,
    RunJobRequest,
    ShellctlModel,
    TerminalSize,
    TerminateJobRequest,
    WaitJobRequest,
)

__all__ = [
    "DEFAULT_AUTH_TOKEN_ENV",
    "DEFAULT_GC_FINISHED_JOB_RETENTION_SECONDS",
    "DEFAULT_GC_INTERVAL_SECONDS",
    "DEFAULT_HEALTH_STATUS",
    "DEFAULT_IDLE_FLUSH_SECONDS",
    "DEFAULT_LIST_LIMIT",
    "DEFAULT_OUTPUT_LIMIT_BYTES",
    "DEFAULT_TERMINAL_COLS",
    "DEFAULT_TERMINAL_ROWS",
    "DEFAULT_TERMINATE_GRACE_SECONDS",
    "DEFAULT_TIMEOUT_SECONDS",
    "JOB_ID_ALPHABET",
    "JOB_ID_RANDOM_SUFFIX_LENGTH",
    "MAX_LIST_LIMIT",
    "MAX_OUTPUT_LIMIT_BYTES",
    "MAX_WAIT_TIMEOUT_SECONDS",
    "SESSION_NAME_PREFIX",
    "TERMINAL_JOB_STATUSES",
    "DeleteJobResponse",
    "ErrorDetail",
    "ErrorResponse",
    "HealthResponse",
    "InputJobRequest",
    "JobInfo",
    "JobResult",
    "JobStatusName",
    "JobStatusView",
    "ListJobsResponse",
    "OutputWindow",
    "PtySanitizer",
    "RunJobRequest",
    "ShellctlModel",
    "TerminalSize",
    "TerminateJobRequest",
    "WaitJobRequest",
    "default_runtime_dir",
    "default_state_dir",
    "format_timestamp",
    "generate_job_id",
    "is_terminal_status",
    "job_pane_target",
    "job_session_name",
    "parse_timestamp",
    "read_output_window",
    "sanitize_pty_output",
    "sanitize_pty_stream",
    "tail_output_window",
    "utc_now",
]
