[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:camoufox_server]
command=/home/k/.kapybara/skills/media/browser/camoufox_server
autostart=true
autorestart=true
stderr_logfile=/home/k/.kapybara/logs/camoufox_server.err.log
stdout_logfile=/home/k/.kapybara/logs/camoufox_server.out.log
user=k
environment=HOME="/home/k",USER="k",XDG_STATE_HOME="/home/k/.local/state"

[program:sshd]
command=/usr/sbin/sshd -D -e
autostart=true
autorestart=true
startsecs=1
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:cron]
command=/usr/sbin/cron -f
autostart=true
autorestart=true
startsecs=1
priority=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:start]
command=/home/k/start.sh
directory=/home/k
user=k
autostart=true
autorestart=true
startsecs=1
priority=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
