"""Add message recording authority

Revision ID: 450323213b20
Revises: aba4ff60dd54
"""

# Alembic renders SQL statements as indivisible string literals.
# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "450323213b20"
down_revision: str | Sequence[str] | None = "aba4ff60dd54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_history",
        sa.Column("authoritative", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_history", "authoritative")
    # ### end Alembic commands ###
