"""Add session context plugin selection

Revision ID: 89b503bfe30c
Revises: f3f3d8c38d58
"""

# Alembic renders SQL statements as indivisible string literals.
# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "89b503bfe30c"
down_revision: str | Sequence[str] | None = "f3f3d8c38d58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "context_plugin",
            sa.JSON(none_as_null=True),
            server_default='{"name":"kapy/summary","config":{}}',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "context_plugin")
    # ### end Alembic commands ###
