"""Separate session leases from runner checkpoints

Revision ID: 99ea34c7be0d
Revises: 12fd53fd60d5
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "99ea34c7be0d"
down_revision: str | Sequence[str] | None = "12fd53fd60d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_leases",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("lock_token", sa.Uuid(), nullable=True),
        sa.Column(
            "heartbeat_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.drop_column("agent_states", "lock_token")
    op.drop_column("agent_states", "heartbeat_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_states",
        sa.Column(
            "heartbeat_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "agent_states", sa.Column("lock_token", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_table("session_leases")
    # ### end Alembic commands ###
