"""Add session runner state

Revision ID: aba4ff60dd54
Revises: 89b503bfe30c
"""

# Alembic renders SQL statements as indivisible string literals.
# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "aba4ff60dd54"
down_revision: str | Sequence[str] | None = "89b503bfe30c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("runner_state", sa.Text(), nullable=True))
    op.add_column(
        "sessions",
        sa.Column("runner_state_version", sa.BigInteger(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "runner_state_version")
    op.drop_column("sessions", "runner_state")
    # ### end Alembic commands ###
