"""Generalize summaries to context pages

Revision ID: eae2fdb48969
Revises: 12fd53fd60d5
"""

# Alembic renders SQL statements as indivisible string literals.
# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "eae2fdb48969"
down_revision: str | Sequence[str] | None = "12fd53fd60d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE agent_compactions RENAME TO agent_context_pages")
    op.alter_column(
        "agent_context_pages",
        "last_message_seq",
        existing_type=sa.Integer(),
        new_column_name="anchor_seq",
    )
    op.add_column("agent_context_pages", sa.Column("policy_key", sa.Text(), nullable=True))
    op.add_column("agent_context_pages", sa.Column("payload", sa.JSON(), nullable=True))
    op.execute(
        "UPDATE agent_context_pages SET policy_key = 'summary/v1', payload = json_build_object('summary', text)"
    )
    op.alter_column("agent_context_pages", "policy_key", existing_type=sa.Text(), nullable=False)
    op.alter_column("agent_context_pages", "payload", existing_type=sa.JSON(), nullable=False)
    op.drop_column("agent_context_pages", "text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DO $$ BEGIN\nIF EXISTS (SELECT 1 FROM agent_context_pages WHERE policy_key <> 'summary/v1'\nOR json_typeof(payload->'summary') IS DISTINCT FROM 'string') THEN\nRAISE EXCEPTION 'Only summary/v1 pages can be downgraded';\nEND IF; END $$"
    )
    op.add_column("agent_context_pages", sa.Column("text", sa.Text(), nullable=True))
    op.execute("UPDATE agent_context_pages SET text = payload->>'summary'")
    op.alter_column("agent_context_pages", "text", existing_type=sa.Text(), nullable=False)
    op.drop_column("agent_context_pages", "payload")
    op.drop_column("agent_context_pages", "policy_key")
    op.alter_column(
        "agent_context_pages",
        "anchor_seq",
        existing_type=sa.Integer(),
        new_column_name="last_message_seq",
    )
    op.execute("ALTER TABLE agent_context_pages RENAME TO agent_compactions")
    # ### end Alembic commands ###
