"""Index history confirmation boundary

Revision ID: f0e75989c93b
Revises: 450323213b20
"""

# Alembic renders SQL statements as indivisible string literals.
# ruff: noqa: E501

from collections.abc import Sequence

from alembic import op

revision: str = "f0e75989c93b"
down_revision: str | Sequence[str] | None = "450323213b20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_agent_history_session_authoritative_seq",
        "agent_history",
        ["session_id", "authoritative", "seq"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_agent_history_session_authoritative_seq", table_name="agent_history")
    # ### end Alembic commands ###
