"""Add agent plugin bindings and session lifecycle

Revision ID: f3f3d8c38d58
Revises: d8fbb0f09711
"""

# Alembic renders SQL statements as indivisible string literals.
# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f3f3d8c38d58"
down_revision: str | Sequence[str] | None = "d8fbb0f09711"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_agent_bindings",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("plugin_provider", sa.Text(), nullable=False),
        sa.Column("plugin_name", sa.Text(), nullable=False),
        sa.Column("data_version", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("state", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("revision", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ready", "closing", "closed", name="lifecyclestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("data_version > 0"),
        sa.PrimaryKeyConstraint("session_id", "plugin_provider", "plugin_name"),
    )
    op.add_column(
        "sessions",
        sa.Column(
            "status",
            sa.Enum("ready", "closing", "closed", name="lifecyclestatus", native_enum=False),
            server_default="ready",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "status")
    op.drop_table("plugin_agent_bindings")
    # ### end Alembic commands ###
