"""Initial core business schema

Revision ID: c83583313120
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c83583313120"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("settings", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("context_window > 0"),
        sa.PrimaryKeyConstraint("provider_id", "model_name"),
    )
    op.create_table(
        "providers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("provider_class", sa.Text(), nullable=False),
        sa.Column("model_class", sa.Text(), nullable=False),
        sa.Column("api_key", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("provider_kwargs", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session_cancels",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "session_inputs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("content", sa.JSON(none_as_null=True), nullable=False),
        sa.CheckConstraint("channel IN ('steer', 'queued')"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "session_inputs_order", "session_inputs", ["session_id", "channel", "id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("model_settings", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("compaction_threshold_tokens", sa.Integer(), nullable=True),
        sa.Column("compaction_replay_turns", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("compaction_replay_turns >= 0"),
        sa.CheckConstraint("compaction_threshold_tokens > 0"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sessions_provider_model", "sessions", ["provider_id", "model_name"], unique=False
    )
    op.create_table(
        "agent_compactions",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("last_message_seq", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint("last_message_seq >= 0"),
        sa.PrimaryKeyConstraint("session_id", "last_message_seq"),
    )
    op.create_table(
        "agent_history",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("message", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("message_metadata", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("finish_reason", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.CheckConstraint("kind IN ('request', 'response')"),
        sa.CheckConstraint("input_tokens IS NULL OR input_tokens >= 0"),
        sa.CheckConstraint("output_tokens IS NULL OR output_tokens >= 0"),
        sa.CheckConstraint("seq >= 0"),
        sa.PrimaryKeyConstraint("session_id", "seq"),
    )
    op.create_table(
        "agent_states",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("next_step", sa.Text(), nullable=False),
        sa.Column("lock_token", sa.Uuid(), nullable=True),
        sa.Column(
            "heartbeat_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint("next_step IN ('model_request', 'handle_response', 'done')"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_states")
    op.drop_table("agent_history")
    op.drop_table("agent_compactions")
    op.drop_index("ix_sessions_provider_model", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("session_inputs_order", table_name="session_inputs")
    op.drop_table("session_inputs")
    op.drop_table("session_cancels")
    op.drop_table("providers")
    op.drop_table("models")
    # ### end Alembic commands ###
