"""Add Telegram default model selection

Revision ID: 4c7a85e5a4ab
Revises: fe6939048398
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4c7a85e5a4ab"
down_revision: str | Sequence[str] | None = "fe6939048398"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_telegram_defaults",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("bot_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plugin_telegram_defaults")
    # ### end Alembic commands ###
