"""Initial Telegram schema

Revision ID: fe6939048398
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fe6939048398"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_telegram_delivery",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("chat_type", sa.Text(), nullable=False),
        sa.Column("after_seq", sa.Integer(), nullable=False),
        sa.Column("pending", sa.JSON(), nullable=True),
        sa.Column("item_offset", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.Float(), nullable=False),
        sa.Column("blocked_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("bot_id", "chat_id", "thread_id", "session_id"),
    )
    op.create_table(
        "plugin_telegram_inbox",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("update_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("resolved_action", sa.JSON(), nullable=True),
        sa.Column("handled", sa.Boolean(), nullable=False),
        sa.Column("next_attempt_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("bot_id", "update_id"),
    )
    op.create_table(
        "plugin_telegram_poll",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("next_update_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("bot_id"),
    )
    op.create_table(
        "plugin_telegram_routes",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("bot_id", "chat_id", "thread_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plugin_telegram_routes")
    op.drop_table("plugin_telegram_poll")
    op.drop_table("plugin_telegram_inbox")
    op.drop_table("plugin_telegram_delivery")
    # ### end Alembic commands ###
